version: "3"

services:
  api:
    build: .
    environment:
      - API_VERSION=1.0.0
    ports:
      - 8080:8080
    restart: always

  prometheus:
    image: prom/prometheus:v2.27.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: always


